#!/bin/bash

set -x

#forApp
echo 'export ECS_CLUSTER="project-cost"' >> $BASH_ENV
echo 'export APP_NAME="project-cost_aweb"' >> $BASH_ENV
echo 'export ECS_SERVICE="project-cost"' >> $BASH_ENV
echo 'export AWS_REGION="ap-northeast-1"' >> $BASH_ENV
echo 'export ECR_AWS_ACCOUNT_ID="${ECR_AWS_ACCOUNT_ID}"' >> $BASH_ENV

if [ "${ENVIRONMENT}" == "production" ]; then
  # forTask
  echo 'export RESERVED_CPU_UNIT=512' >> $BASH_ENV
  echo 'export RESERVED_MEMORY=1024' >> $BASH_ENV
  # for AWS
  echo "APP_S3_UPLOAD=${APP_S3_UPLOAD_PRODUCTION}" >> $BASH_ENV
  #for datadog
  echo 'export DD_APM_ENABLED="true"' >> $BASH_ENV
  echo 'export DD_LOGS_ENABLED="true"' >> $BASH_ENV
  echo 'export DD_ENV="production"' >> $BASH_ENV
  # for FE & BE
  echo "APP_FE=${APP_PRODUCTION}" >> .env
  echo "APP_BE=${APP_PRODUCTION}" >> .env
  # for AzureAD
  echo "APP_AZURE_AD_TENANT_ID=${APP_AZURE_AD_TENANT_ID_PRODUCTION}" >> .env
  echo "APP_AZURE_AD_CLIENT_ID=${APP_AZURE_AD_CLIENT_ID_PRODUCTION}" >> .env
  
  # for MFID & NAVIS
  echo "APP_CLIENT_ID=${APP_CLIENT_ID_PRODUCTION}" >> .env
  echo "APP_NAVIS_BASE=${APP_NAVIS_BASE_PRODUCTION}" >> .env
  echo "APP_ACCOUNTING_PLUS_BASE=${APP_ACCOUNTING_PLUS_BASE_PRODUCTION}" >> .env
  echo "APP_INQUIRY_LINK=${APP_INQUIRY_LINK}" >> .env
  ###
elif [ "${ENVIRONMENT}" == "staging" ]; then
  # for Task
  echo 'export RESERVED_CPU_UNIT=512' >> $BASH_ENV
  echo 'export RESERVED_MEMORY=1024' >> $BASH_ENV
  # for AWS
  echo 'export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_STAGING}"' >> $BASH_ENV
  echo 'export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_STAGING}"' >> $BASH_ENV
  echo 'export CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID_STAGING}"' >> $BASH_ENV
  echo "APP_S3_UPLOAD=${APP_S3_UPLOAD_STAGING}" $BASH_ENV
  # for datadog
  echo 'export DD_APM_ENABLED="false"' >> $BASH_ENV
  echo 'export DD_LOGS_ENABLED="true"' >> $BASH_ENV
  echo 'export DD_ENV="staging"' >> $BASH_ENV
  # for FE & BE
  echo "APP_FE=${APP_STAGING}" >> .env
  echo "APP_BE=${APP_STAGING}" >> .env
  # for AzureAD
  echo "APP_AZURE_AD_TENANT_ID=${APP_AZURE_AD_TENANT_ID_STAGING}" >> .env
  echo "APP_AZURE_AD_CLIENT_ID=${APP_AZURE_AD_CLIENT_ID_STAGING}" >> .env
  
  # for MFID & NAVIS
  echo "APP_CLIENT_ID=${APP_CLIENT_ID_STAGING}" >> .env
  echo "APP_NAVIS_BASE=${APP_NAVIS_BASE_STAGING}" >> .env
  echo "APP_ACCOUNTING_PLUS_BASE=${APP_ACCOUNTING_PLUS_BASE_STAGING}" >> .env
  echo "APP_INQUIRY_LINK=${APP_INQUIRY_LINK_STAGING}" >> .env
elif [ "${ENVIRONMENT}" == "beta" ]; then
  # for Task
  echo 'export RESERVED_CPU_UNIT=512' >> $BASH_ENV
  echo 'export RESERVED_MEMORY=1024' >> $BASH_ENV
  # for AWS
  echo 'export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_STAGING}"' >> $BASH_ENV
  echo 'export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_STAGING}"' >> $BASH_ENV
  echo 'export CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID_STAGING}"' >> $BASH_ENV
  echo "APP_S3_UPLOAD=${APP_S3_UPLOAD_STAGING}" $BASH_ENV
  # for datadog
  echo 'export DD_APM_ENABLED="false"' >> $BASH_ENV
  echo 'export DD_LOGS_ENABLED="true"' >> $BASH_ENV
  echo 'export DD_ENV="staging"' >> $BASH_ENV
  # for FE & BE
  echo "APP_FE=${APP_BETA}" >> .env
  echo "APP_BE=${APP_BETA}" >> .env
  # for AzureAD
  echo "APP_AZURE_AD_TENANT_ID=${APP_AZURE_AD_TENANT_ID_STAGING}" >> .env
  echo "APP_AZURE_AD_CLIENT_ID=${APP_AZURE_AD_CLIENT_ID_STAGING}" >> .env
  
  # for MFID & NAVIS
  echo "APP_CLIENT_ID=${APP_CLIENT_ID_BETA}" >> .env
  echo "APP_NAVIS_BASE=${APP_NAVIS_BASE_STAGING}" >> .env
  echo "APP_ACCOUNTING_PLUS_BASE=${APP_ACCOUNTING_PLUS_BASE_STAGING}" >> .env
  echo "APP_INQUIRY_LINK=${APP_INQUIRY_LINK_STAGING}" >> .env
fi